# Generated by Django 4.1.3 on 2022-12-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_facultycse'),
    ]

    operations = [
        migrations.CreateModel(
            name='burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField(max_length=100)),
            ],
        ),
    ]
