# Generated by Django 4.1.3 on 2022-12-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_chinese_hotbeverages_maggi_shake_snacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='image',
            field=models.ImageField(default='', upload_to='menu/images'),
        ),
    ]
