# Generated by Django 4.1.3 on 2022-12-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menus_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='image',
            field=models.ImageField(default='', upload_to='menu/images'),
        ),
        migrations.AddField(
            model_name='chinese',
            name='image',
            field=models.ImageField(default='', upload_to='menu/images'),
        ),
        migrations.AddField(
            model_name='facultycse',
            name='image',
            field=models.ImageField(default='', upload_to='menu/images'),
        ),
        migrations.AddField(
            model_name='hotbeverages',
            name='image',
            field=models.ImageField(default='', upload_to='menu/images'),
        ),
        migrations.AddField(
            model_name='maggi',
            name='image',
            field=models.ImageField(default='', upload_to='menu/images'),
        ),
        migrations.AddField(
            model_name='shake',
            name='image',
            field=models.ImageField(default='', upload_to='menu/images'),
        ),
        migrations.AddField(
            model_name='snacks',
            name='image',
            field=models.ImageField(default='', upload_to='menu/images'),
        ),
    ]
