# Generated by Django 4.1.3 on 2022-12-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_burger_image_chinese_image_facultycse_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='item_price',
            field=models.CharField(max_length=100),
        ),
    ]
