# Generated by Django 4.1.3 on 2022-12-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_burger_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='item_price',
            field=models.IntegerField(max_length=100),
        ),
    ]
