# Generated by Django 4.1.3 on 2022-12-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_burger_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='coolref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='menu/images')),
            ],
        ),
        migrations.CreateModel(
            name='egg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='menu/images')),
            ],
        ),
        migrations.CreateModel(
            name='garlicbread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='menu/images')),
            ],
        ),
        migrations.CreateModel(
            name='mocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='menu/images')),
            ],
        ),
        migrations.CreateModel(
            name='parantha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='menu/images')),
            ],
        ),
        migrations.CreateModel(
            name='pastries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='menu/images')),
            ],
        ),
        migrations.CreateModel(
            name='pudding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='menu/images')),
            ],
        ),
        migrations.CreateModel(
            name='sandwich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='menu/images')),
            ],
        ),
    ]
