# Generated by Django 4.1.3 on 2022-12-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_coolref_egg_garlicbread_mocktail_parantha_pastries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_burgerid', models.CharField(max_length=50)),
                ('item_hotbevid', models.CharField(max_length=50)),
                ('item_maggiid', models.CharField(max_length=50)),
                ('item_shakeid', models.CharField(max_length=50)),
                ('item_snacksid', models.CharField(max_length=50)),
                ('item_chineseid', models.CharField(max_length=50)),
                ('item_puddingid', models.CharField(max_length=50)),
                ('item_sandwichid', models.CharField(max_length=50)),
                ('item_garlicid', models.CharField(max_length=50)),
                ('item_coolrefid', models.CharField(max_length=50)),
                ('item_paranthaid', models.CharField(max_length=50)),
                ('item_mocktailid', models.CharField(max_length=50)),
                ('item_eggid', models.CharField(max_length=50)),
            ],
        ),
    ]
