# Generated by Django 4.1.3 on 2023-01-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_menus_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='PASSWORD',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='USERNAME',
        ),
        migrations.RemoveField(
            model_name='login',
            name='phone',
        ),
        migrations.AddField(
            model_name='login',
            name='EMAILID',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
